### ISSUE TITLE
Error when changing background color

### ISSUE THREAD

**Issue by Baltharu5** [rursache/InFlight-TWW#20]
Getting two errors when trying to change the background color:

Message: Interface/AddOns/InFlight/InFlight.lua:913: attempt to index global 'OpacitySliderFrame' (a nil value)
Time: Tue Aug 27 20:02:07 2024
Count: 1
Stack: Interface/AddOns/InFlight/InFlight.lua:913: attempt to index global 'OpacitySliderFrame' (a nil value)
[string "@Interface/AddOns/InFlight/InFlight.lua"]:913: in function `swatchFunc'
[string "@Interface/AddOns/Blizzard_FrameXML/Mainline/ColorPickerFrame.lua"]:8: in function <...dOns/Blizzard_FrameXML/Mainline/ColorPickerFrame.lua:4>
[string "=[C]"]: in function `SetColorRGB'
[string "@Interface/AddOns/Blizzard_FrameXML/Mainline/ColorPickerFrame.lua"]:75: in function `SetupColorPickerAndShow'
[string "@Interface/AddOns/Blizzard_SharedXML/Mainline/UIDropDownMenu.lua"]:1476: in function `UIDropDownMenuButton_OpenColorPicker'
[string "*UIDropDownMenuTemplates.xml:50_OnClick"]:2: in function <[string "*UIDropDownMenuTemplates.xml:50_OnClick"]:1>

Locals: a1 = nil
dbc = <table> {
 a = 0.600000
 b = 0.101961
 g = 0.101961
 r = 0.101961
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0.101961
(*temporary) = 0.101961
(*temporary) = 0.101961
(*temporary) = "attempt to index global 'OpacitySliderFrame' (a nil value)"
db = <table> {
 outline = true
 backcolor = <table> {
 }
 barcolor = <table> {
 }
 border = "None"
 fontsize = 12
 outlinetime = true
 rp = "CENTER"
 totext = "-->"
 twolines = false
 texture = "TheWarWithinBar"
 spark = true
 p = "CENTER"
 confirmflight = false
 x = 0
 font = "2002 Bold"
 bordercolor = <table> {
 }
 inline = true
 width = 390
 y = -239
 chatlog = true
 unknowncolor = <table> {
 }
 fill = true
 height = 28
 perchar = false
 fontcolor = <table> {
 }
 countup = false
}
InFlight = InFlight {
 defaults = <table> {
 }
 db = <table> {
 }
 L = <table> {
 }
 debug = false
}
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Message: Interface/AddOns/InFlight/InFlight.lua:913: attempt to index global 'OpacitySliderFrame' (a nil value)
Time: Tue Aug 27 20:02:07 2024
Count: 1
Stack: Interface/AddOns/InFlight/InFlight.lua:913: attempt to index global 'OpacitySliderFrame' (a nil value)
[string "@Interface/AddOns/InFlight/InFlight.lua"]:913: in function `swatchFunc'
[string "@Interface/AddOns/Blizzard_FrameXML/Mainline/ColorPickerFrame.lua"]:8: in function <...dOns/Blizzard_FrameXML/Mainline/ColorPickerFrame.lua:4>
[string "=[C]"]: in function `SetColorAlpha'
[string "@Interface/AddOns/Blizzard_FrameXML/Mainline/ColorPickerFrame.lua"]:39: in function <...dOns/Blizzard_FrameXML/Mainline/ColorPickerFrame.lua:34>
[string "=[C]"]: in function `Show'
[string "@Interface/AddOns/Blizzard_FrameXML/Mainline/ColorPickerFrame.lua"]:76: in function `SetupColorPickerAndShow'
[string "@Interface/AddOns/Blizzard_SharedXML/Mainline/UIDropDownMenu.lua"]:1476: in function `UIDropDownMenuButton_OpenColorPicker'
[string "*UIDropDownMenuTemplates.xml:50_OnClick"]:2: in function <[string "*UIDropDownMenuTemplates.xml:50_OnClick"]:1>

Locals: a1 = nil
dbc = <table> {
 a = 0.600000
 b = 0.101961
 g = 0.101961
 r = 0.101961
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 0.101961
(*temporary) = 0.101961
(*temporary) = 0.101961
(*temporary) = "attempt to index global 'OpacitySliderFrame' (a nil value)"
db = <table> {
 outline = true
 backcolor = <table> {
 }
 barcolor = <table> {
 }
 border = "None"
 fontsize = 12
 outlinetime = true
 rp = "CENTER"
 totext = "-->"
 twolines = false
 texture = "TheWarWithinBar"
 spark = true
 p = "CENTER"
 confirmflight = false
 x = 0
 font = "2002 Bold"
 bordercolor = <table> {
 }
 inline = true
 width = 390
 y = -239
 chatlog = true
 unknowncolor = <table> {
 }
 fill = true
 height = 28
 perchar = false
 fontcolor = <table> {
 }
 countup = false
}
InFlight = InFlight {
 defaults = <table> {
 }
 db = <table> {
 }
 L = <table> {
 }
 debug = false
}

**Comment by Baltharu5** [comment]
I just tested, and these error pop up with any of the color picker options for the bar and the text.

**Comment by superwario15** [comment]
I believe I've fixed this issue with https://github.com/rursache/InFlight-TWW/pull/21.

**Comment by rursache** [comment]
seems the issue still happens :( 
https://github.com/rursache/InFlight-TWW/issues/24

**Comment by rursache** [comment]
v11.0.7 of the addon was submitted to curseforge. the updated version have the fix for this issue
